/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sn.ugb.ipsl.gui_gestion_etudiant;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mohamed
 */
public class GestionEtudiant extends javax.swing.JFrame {

    /**
     * Creates new form GestionEtudiant
     */
    public GestionEtudiant() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        AjouterEtudiantMenu = new javax.swing.JMenu();
        AjouterMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AjouterFiliereMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ListeFiliereMenuItem = new javax.swing.JMenuItem();
        ListeClasseMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 20, 510, 260);

        AjouterEtudiantMenu.setText("Ajouter");

        AjouterMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        AjouterMenuItem.setText("Ajouter étudiants");
        AjouterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterMenuItemActionPerformed(evt);
            }
        });
        AjouterEtudiantMenu.add(AjouterMenuItem);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Supprimer étudiants");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        AjouterEtudiantMenu.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Modifier étudiants");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        AjouterEtudiantMenu.add(jMenuItem2);

        jMenuBar1.add(AjouterEtudiantMenu);

        jMenu2.setText("Filiere");

        AjouterFiliereMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        AjouterFiliereMenuItem.setText("Ajouter Filière");
        AjouterFiliereMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterFiliereMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(AjouterFiliereMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Liste ");

        ListeFiliereMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ListeFiliereMenuItem.setText("Liste étudiants d'une filière");
        ListeFiliereMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeFiliereMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(ListeFiliereMenuItem);

        ListeClasseMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ListeClasseMenuItem.setText("Liste étudiants d'une classe");
        ListeClasseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeClasseMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(ListeClasseMenuItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterMenuItemActionPerformed
        AjouterEtudiant contenu = null;
        try {
            contenu = new AjouterEtudiant();
        } catch (SQLException ex) {
            Logger.getLogger(GestionEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        setContentPane(contenu);
        repaint();
        validate();
    }//GEN-LAST:event_AjouterMenuItemActionPerformed

    private void AjouterFiliereMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterFiliereMenuItemActionPerformed
       AjouterFiliere pane = null;
        try {
            pane = new AjouterFiliere();
        } catch (SQLException ex) {
            Logger.getLogger(GestionEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        setContentPane(pane);
        repaint();
        validate();
    }//GEN-LAST:event_AjouterFiliereMenuItemActionPerformed

    private void ListeFiliereMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeFiliereMenuItemActionPerformed
        ListeEtudiantFiliere contenu = new ListeEtudiantFiliere();
        setContentPane(contenu);
        repaint();
        validate();
    }//GEN-LAST:event_ListeFiliereMenuItemActionPerformed

    private void ListeClasseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeClasseMenuItemActionPerformed
        ListeEtudiantClasse contenu = null;
        try {
            contenu = new ListeEtudiantClasse();
        } catch (SQLException ex) {
            Logger.getLogger(GestionEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        setContentPane(contenu);
        repaint();
        validate();
    }//GEN-LAST:event_ListeClasseMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      AjouterEtudiant contenu = null;
        try {
            contenu = new AjouterEtudiant();
        } catch (SQLException ex) {
            Logger.getLogger(GestionEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        setContentPane(contenu);
        repaint();
        validate();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         AjouterEtudiant contenu = null;
        try {
            contenu = new AjouterEtudiant();
        } catch (SQLException ex) {
            Logger.getLogger(GestionEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        setContentPane(contenu);
        repaint();
        validate();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionEtudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AjouterEtudiantMenu;
    private javax.swing.JMenuItem AjouterFiliereMenuItem;
    private javax.swing.JMenuItem AjouterMenuItem;
    private javax.swing.JMenuItem ListeClasseMenuItem;
    private javax.swing.JMenuItem ListeFiliereMenuItem;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
